version: '3'

services:
  app: 
    container_name: docker-node-mongo
    restart: always
    build: . # This tells it to look in the current directory for the dockerfile
    ports:
      - '80:3000'
    links: 
      - mongo
  mongo: 
    container_name: mongo
    image: centos/mongodb-32-centos7 # using image because we're pulling the image from docker not building
    # image: mongo
    ports:
      - '27017:27017'
    env_file:
      - mongo.env
    